## -- libraries --
library(dplyr)
library(stringr)
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(shinycssloaders)
library(DT)
library(readxl)
library(writexl)
library(here)
setwd(here())



## -- common functions and global variables --
source("functions/utils.R")
appColors <- c("#00AAAD", "#007681", "#004F66", "#132A3E")

# path <- "C:/Users/CABRERJO/International Organization for Migration - IOM/Regional Cordination Platform - General/IM/JNAs & Sector Guides/PiN Indicators 2024/Compilado de fichas (post-taller Dec 23)/Respuesta final de sectores"
# SourceJNA2024Indicators <- read_excel(
#   paste(path, "Compilado de fichas sectores_FINAL.xlsx", sep="/"),
#   sheet = "DB_MERGED") %>%
#   select(1:15)

# Save dataframe to RDS
#saveRDS(SourceJNA2024Indicators, "datasource/JNAToolkitDF.RDS")

# Read dataframe from RDS
#read_dataframe_rds <- readRDS("datasource/JNAToolkitDF.RDS")

SourceJNA2024Indicators <- structure(list(Sector = c("Educación", "Educación", "Educación", 
                                                     "Educación", "Educación", "Educación", "Educación", "Educación", 
                                                     "Educación", "Educación", "Educación", "Educación", "Educación", 
                                                     "Integración", "Integración", "Integración", "Integración", 
                                                     "Integración", "Integración", "Integración", "Integración", 
                                                     "Integración", "Integración"), Unique_Q_ID = c("EDU_D1_Q1", 
                                                                                                    "EDU_D2_Q1", "EDU_D2_Q2", "EDU_D3_Q1", "EDU_D4_Q1", "EDU_D5_Q1", 
                                                                                                    "EDU_D6_Q1", "EDU_D7_Q1", "EDU_T1_Q1", "EDU_T2_Q1", "EDU_T3_Q1", 
                                                                                                    "EDU_T4_Q1", "EDU_T5_Q1", "INT_D1_Q1", "INT_D2_Q1", "INT_D2_Q2", 
                                                                                                    "INT_D2_Q3", "INT_D3_Q1", "INT_D3_Q2", "INT_D4_Q1", "INT_D5_Q1", 
                                                                                                    "INT_T1_Q1", "INT_T2_Q1"), Ind_ID = c("EDU_D1", "EDU_D2", "0", 
                                                                                                                                          "EDU_D3", "EDU_D4", "EDU_D5", "EDU_D6", "EDU_D7", "EDU_T1", "EDU_T2", 
                                                                                                                                          "EDU_T3", "EDU_T4", "EDU_T5", "INT_D1", "INT_D2", "0", "0", "INT_D3", 
                                                                                                                                          "0", "INT_D4", "INT_D5", "INT_T1", "INT_T2"), `Tipo de población` = c("Destino", 
                                                                                                                                                                                                                "Destino", "0", "Destino", "Destino", "Destino", "Destino", "Destino", 
                                                                                                                                                                                                                "Tránsito", "Tránsito", "Tránsito", "Tránsito", "Tránsito", 
                                                                                                                                                                                                                "Destino", "Destino", "0", "0", "Destino", "-", "Destino", "Destino", 
                                                                                                                                                                                                                "Transito", "Transito"), `Redaccion del indicador` = c("% de NNA refugiados y migrantes que no están inscritos en el sistema escolar formal", 
                                                                                                                                                                                                                                                                       "% de NNA refugiados y migrantes ente los 0 y 3 años que no cuentan con un servicio de atención de desarrollo temprano ni cuidado adecuado", 
                                                                                                                                                                                                                                                                       "0", "% de NNA refugiados y migrantes que no asisten al centro educativo (CE) o centro de atencion de primera (CAPI) infacia de manera regular", 
                                                                                                                                                                                                                                                                       "% de NNA refugiados y migrantes que no han podido hacer Reconocimiento, validación o acreditación (RVA) de sus estudios anteriores", 
                                                                                                                                                                                                                                                                       "-", "-", "-", "% de NNA refugiados y migrantes en tránsito que no han recibido servicios de educación durante su trayecto (desde que salió de su país de origen o punto de partida a la fecha)", 
                                                                                                                                                                                                                                                                       "-", "-", "-", "-", "Porcentaje de personas en desempleo", "Porcentaje de personas con trabajos informales", 
                                                                                                                                                                                                                                                                       "0", "0", "Porcentaje de personas que se han sentido discriminadas en el espacio laboral o de emprendimiento/autoempleo", 
                                                                                                                                                                                                                                                                       "0", "Porcentaje de personas encuestadas que no tienen acceso a servicios financieros", 
                                                                                                                                                                                                                                                                       "-", "Porcentaje de personas en los grupos de viaje que tienen necesidad de generación de ingresos", 
                                                                                                                                                                                                                                                                       "-"), `Propósito del indicador` = c("Identificar los NNA que NO están inscritos al sistema escolar", 
                                                                                                                                                                                                                                                                                                           "Identificar los NNA menores de 3 años que no cuentan con un servicio de atención al desarrollo temprano, así como los que no cuentan con cuidado adecuado", 
                                                                                                                                                                                                                                                                                                           "0", "Identificar a los NNA que no asistieron regularmente al sistema educativo en el último mes", 
                                                                                                                                                                                                                                                                                                           "Identificar a la población que NO ha logrado el proceso de Reconocimiento, Validación o Acreditación (RVA) de sus estudios anteriores", 
                                                                                                                                                                                                                                                                                                           "Identificar a la población que NO ha logrado el proceso de Reconocimiento, Validación o Acreditación (RVA) de sus estudios anteriores", 
                                                                                                                                                                                                                                                                                                           "Pregunta complementaria al indicador de inscripcion al sistema educativo", 
                                                                                                                                                                                                                                                                                                           "Pregunta complementaria al indicador de asistencia al sistema educativo", 
                                                                                                                                                                                                                                                                                                           "Identificar la población en tránsito que NO ha recibido servicios educativos en la ruta migratoria", 
                                                                                                                                                                                                                                                                                                           "Identificar a la población en tránsito que NO ha recibido la información necesaria sobre servicios educativos en la ruta mgiratoria", 
                                                                                                                                                                                                                                                                                                           "Pregunta complementaria 1 al indicador , no obligatoria", "Pregunta complementaria 2 al indicador, no obligatoria", 
                                                                                                                                                                                                                                                                                                           "Pregunta complementaria 3 al indicador, no obligatoria", "Calcular las personas en edad laboral en desempleo. Para ellos podemos dirigir nuestras intervenciones del sector para mejorar el acceso al mercado de trabajo", 
                                                                                                                                                                                                                                                                                                           "Calcular las personas en edad laboral en informalidad. Para ellos podemos dirigir nuestras intervenciones del sector para mejorar la calidad del empleo", 
                                                                                                                                                                                                                                                                                                           "0", "0", "Medir el nivel de discriminación por nacionalidad en el ambito laboral así los socios del sector pueden abordar de manera específica esta problemática, que impide la integración.", 
                                                                                                                                                                                                                                                                                                           "0", "Medir el acceso a servicios financieros indica la facilidad que puedan tener las personas para hacer parte del sistema financiero y acceder a formas actuales del manejo del dinero. Por ejemplo, posibilidades para tener ahorros seguros, acceso a prestamos, facilidad para pagos de bienes y servicios entre otros. La inclusion de las personas en el sistema financiero contribuye con el desarrollo económico de los paises", 
                                                                                                                                                                                                                                                                                                           "Conocer cuántas personas en el hogar viven con ingresos por debajo del salario minimo es un buen indicador para aproximar el nivel de pobreza y necesidad de un hogar", 
                                                                                                                                                                                                                                                                                                           "Medir el nivel de necesidad de las personas en tránsito en relación a la generación de ingresos.", 
                                                                                                                                                                                                                                                                                                           "Medir el nivel de necesidad de las personas en tránsito en relación a la generación de ingresos."
                                                                                                                                                                                                                                                                       ), Pregunta = c("Actualmente, ¿El/la NNA está inscrito/a en un centro de desarrollo infantil (servicios de primera infancia, preescolar, parvulario, etc) o centro educativo (primaria, secundaria o bachillerato)? del país de acogida/destino?", 
                                                                                                                                                                                                                                                                                       "Actualmente, ¿El/la NNA está inscrito/a en un centro de desarrollo infantil (servicios de primera infancia, preescolar, parvulario, etc) o centro educativo (primaria, secundaria o bachillerato)? del país de acogida/destino?", 
                                                                                                                                                                                                                                                                                       "¿El NNA permanece el mayor tiempo bajo el cuidado de: \r\n", 
                                                                                                                                                                                                                                                                                       "En promedio, en los últimos 3 meses, ¿cuántos días a la semana este NNA asistió al centro de desarrollo infantil (servicios de primera infancia, preescolar, parvulario, etc) o centro educativo (primaria, secundaria o bachillerato)?", 
                                                                                                                                                                                                                                                                                       "¿El/la NNA ha requerido y finalizado su  proceso de reconocimiento, validación o acreditación de estudios?", 
                                                                                                                                                                                                                                                                                       "¿cuál/les son/han sido los motivos/causas/barreras por las que no ha podido realizar el reconocimiento, validación o acreditación de estudios?", 
                                                                                                                                                                                                                                                                                       "¿cuál/les es/son los motivos/causas/barreras por las que no ha inscrito al NNA al sistema educativo?", 
                                                                                                                                                                                                                                                                                       "¿cuál/les es/son los motivos/causas/barreras por las que el NNA no asistió al sistema escolegar de manera regular?", 
                                                                                                                                                                                                                                                                                       "¿El/la NNA ha recibido un servicio de educación durante su trayecto (desde que salió de su país de origen o punto de partida a la fecha)?", 
                                                                                                                                                                                                                                                                                       "¿Su grupo de viaje ha recibido información sobre los servicios de educación existentes en la ruta migratoria (desde que salió de su país de origen o punto de partida a la fecha)?", 
                                                                                                                                                                                                                                                                                       "¿Le ha sido útil la información?", "¿Quién le entregó la información?", 
                                                                                                                                                                                                                                                                                       "¿Sobre qué tipo de servicios ha sido informado?", "¿Durante la última semana, esta persona a qué actividad dedicó la mayor parte del tiempo?", 
                                                                                                                                                                                                                                                                                       "Si se encuentra trabajando, ¿tiene algún contrato laboral o brinda recibo por sus servicios ?", 
                                                                                                                                                                                                                                                                                       "Si se encuentra trabajando, ¿tiene acceso a la seguridad social en salud en virtud de su empleo?", 
                                                                                                                                                                                                                                                                                       "Si se encuentra trabajando, ¿tiene acceso a la seguridad social en pensiones en virtud de su empleo?", 
                                                                                                                                                                                                                                                                                       "En los últimos 12 meses, ¿Usted o algún miembro de su hogar ha experimentado alguna situación de discriminación y a razón de qué?", 
                                                                                                                                                                                                                                                                                       "En que ámbito se ha(n) sentido discriminado(s)?", "¿Qué tipo de productos financieros tiene su hogar actualmente en el pais en el que se encuentra?\r\n(Pista: Esta pregunta hace referencia al acceso a productos financieros bancarios, no es una pregunta orientada a el prestamista de un fondo ni mucho menos si fue de un tercero o de un banco.)", 
                                                                                                                                                                                                                                                                                       "¿En cuál de los siguientes rangos se encuentran los ingresos **mensuales** por este trabajo?", 
                                                                                                                                                                                                                                                                                       "Si su intención es transitar por este país, ¿cuál es su principal fuente de ingresos para sostenerse a usted y el grupo con el que viaja?", 
                                                                                                                                                                                                                                                                                       "Es esta fuente de ingresos suficientes para cubrir sus gastos durante el tránsito?"
                                                                                                                                                                                                                                                                       ), Tipo = c("Selección única", "Selección única", "Selección única", 
                                                                                                                                                                                                                                                                                   "Número entero", "Selección única", "Selección múltiple", 
                                                                                                                                                                                                                                                                                   "Selección múltiple", "Selección múltiple", "Selección única", 
                                                                                                                                                                                                                                                                                   "Selección múltiple", "Selección única", "Selección múltiple", 
                                                                                                                                                                                                                                                                                   "Selección múltiple", "Selección única", "Selección única", 
                                                                                                                                                                                                                                                                                   "Selección única", "Selección única", "Selección múltiple", 
                                                                                                                                                                                                                                                                                   "Selección múltiple", "Selección múltiple", "Selección única", 
                                                                                                                                                                                                                                                                                   "Selección unica", "Selección unica"), `Opciones de respuesta` = c("Sí; \r\nNo; \r\nNo sabe; \r\nPrefiere no responder", 
                                                                                                                                                                                                                                                                                                                                                      "Sí; \r\nNo; \r\nNo sabe; \r\nPrefiere no responder", "En el trabajo con su padre o madre o cuidador; \r\nEn la vivienda con su padre o madre;  \r\nEn la vivienda donde vive el niño(a) bajo el cuidado de una persona mayor de 18 años; \r\nEn la vivienda donde vive el niño(a), al cuidado de una persona menor de 18 años; \r\nEn la vivienda, solo/a; \r\nEn otro lugar (diferente a la vivienda del niño/a), al cuidado de un pariente o de otra persona; \r\nNo sabe; \r\nPrefiere no responder;", 
                                                                                                                                                                                                                                                                                                                                                      "-", "Si; \r\nNo\r\n", "No ha tenido información suficiente sobre el RVA; \r\nNo ha contado con orientación de RVA; \r\nNo cuenta con los documentos requeridos para la RVA; \r\nNo cuenta con recursos económicos para poder hacer el RVA; \r\nOtro, especifique:", 
                                                                                                                                                                                                                                                                                                                                                      "No ha tenido información/asesoría sobre como ingresar al sistema educativo; \r\nEl sistema educativo no cuenta con cupos suficientes para inscribirse o matricularse; \r\nEl sistema educativo no cuenta con sistema de educación flexible; \r\nEl sistema educativo no cuenta con herramientas pedagógicas o formación para inscribir al NNA que no habla en el idioma del país de destino/acogida; (para el caso que aplique); \r\nEl/la NNA tiene más edad que la que corresponde el nivel educativo que debe cursar (sobreedad); \r\nEl/la NNA no posee documetos requeridos para inscribirse o matricularse; \r\nEl sistema educativo no reconoce los documentos presentados para la inscripción del NNA; \r\nEl/la NNA ha sido discriminado al tratar de inscribirse o matricularse o cuando asiste a la centro educativo; \r\nNo tiene recursos para pagar costos de matrícula, adquirir materiales aducativos y recursos pedagógicos o uniforme escolar entre otros; \r\nEl grupo familiar o NNA no cuenta con recursos para el transporte al centro educativo; \r\nEl/la NNA debe apoyar con los medios de subsistencia del grupo familiar; \r\nEl/la NNA debe apoyar los quehaceres domésticos del grupo familiar; \r\nEl/la NNA debe apoyar el cuidado de algún miembro del grupo familiar; \r\nOtro, especifique:\r\n", 
                                                                                                                                                                                                                                                                                                                                                      "El grupo familiar o NNA no cuenta con dispositivos digitales o acceso a Internet; \r\nEl grupo familiar o NNA no cuenta con recursos para el transporte al centro educativo; \r\nNo hay transporte disponible o asequible para asistir a la centro educativo o centro educativo; \r\nLa centro educativo o centro educativo queda muy lejos del lugar de residencia;\r\nEl/la NNA debe apoyar con los medios de subsistencia del grupo familiar; \r\nEl/la NNA debe apoyar los quehaceres domésticos del grupo familiar; \r\nEl/la NNA debe apoyar el cuidado de algún miembro del grupo familiar; \r\nEl/la NNA ha experimentado discriminación en el sistema escolar; \r\nEl sistema educativo no cuenta con sistema de educación flexible; \r\nEl/la NNA tiene alguna discapacidad; \r\nSeguridad durante el trayecto a la centro educativo/centro educativo; \r\nOtro, especifique:", 
                                                                                                                                                                                                                                                                                                                                                      "Si, ha recibido servicio de aprendizaje presencial;\r\nSi, ha recibido servicio de aprendizaje virtual;\r\nSi, ha recibido un diagnostico de habilidades (competencias básicas de lectura, escritura, matematicas, habilidades socio-emocionales);\r\nSi, ha recibido dotación de asistencia directa en especie (material educativo, dispositivos electrónicos, libros, guías);\r\nSi, ha recibido dotación de asistencia directa a través de ayuda monetaria (multipropósito, transferencias condicionadas para ciertos servicios, datos de Internet, etc);\r\nSi, ha recibido otro tipo de asistencia, especifique:\r\nNo ha recibido ningun tipo de asistencia educativa", 
                                                                                                                                                                                                                                                                                                                                                      "Si ha recibido Información por medios digitales;\r\nSi ha recibido Información Impresa;\r\nSi ha recibido Información de manera oral;\r\nSi ha recibido Información a traves de la Radio;\r\nSi ha recibido Información a traves de la TV;\r\nSi ha recibido Información a traves de Otra forma, especifique; \r\nNo ha recibido información", 
                                                                                                                                                                                                                                                                                                                                                      "Muy útil; \r\nÚtil; \r\nInútil", "Espacio de apoyo;\r\nONG;\r\nInstancia del gobierno;\r\nPolicía o militar;\r\nAutoridad de migración;\r\nIglesia;\r\nUna persona en el camino;\r\nNo sabe;\r\nOtro, especifique:", 
                                                                                                                                                                                                                                                                                                                                                      "Proceso de aprendizaje presencial; \r\nProceso de aprendizaje virtual; \r\nDotación de asistencia en especie (material educativo, dispositivos electrónicos, libros, guías); \r\nDotación de asistencia directa en CVA (multipropósito, transferencias condicionadas para ciertos servicios, datos de internet, etc); \r\nEvaluación de competencias básicas; \r\nOtro, especifique:", 
                                                                                                                                                                                                                                                                                                                                                      "Trabajar; \r\nBuscar trabajo; \r\nEstudiar; \r\nOficios del hogar; \r\nEstá incapacitado/a permanentemente para trabajar; \r\nOtra actividad", 
                                                                                                                                                                                                                                                                                                                                                      "Sí; \r\nNo; \r\nNo sabe/No responde", "Sí; \r\nSí y mi empleador aporta un porcentaje menor o mayor de lo que corresponde a mi salario; \r\nNo; \r\nNo sabe/ No responde", 
                                                                                                                                                                                                                                                                                                                                                      "Sí; \r\nSí y mi empleador aporta un porcentaje menor o mayor de lo que corresponde a mi salario; \r\nNo; \r\nNo sabe/ No responde", 
                                                                                                                                                                                                                                                                                                                                                      "No; \r\nSi, a razon de mi edad; \r\nSi, por mi sexo (hombre, mujer); \r\nSi, por mi orientación sexual (gays, lesbianas, bisexuales); \r\nSi, por mi identidad de género diversa (mujeres trans, hombres trans, no binario); \r\nSi, por mi etnia; \r\nSi, por tener discapacidad; \r\nSi, por mi nacionalidad;                     \r\nOtra razón; \r\nNo sabe; \r\nPrefiere no responder\r\n", 
                                                                                                                                                                                                                                                                                                                                                      "En el trabajo; \r\nBuscando trabajo; \r\nEn el sistema educativo; \r\nEn el acceso a servicios prestados por el gobierno; \r\nEn el acceso a vivienda; \r\nEn el mercado; \r\nEn su barrio/comunidad; \r\nOtro; \r\nNo sabe; \r\nPrefiere no responder", 
                                                                                                                                                                                                                                                                                                                                                      "Cuenta corriente; \r\nCuenta de ahorros con alguna entidad financiera; \r\nBilletera electrónica; \r\nMicrocrédito; \r\nCertificados de Depósito a Término/Plazo (ajustar con el nombre que use cada pais); \r\nPréstamo para compra de vivienda;  \r\nPréstamo para compra de vehículo; \r\nPréstamo de libre inversión; \r\nTarjeta de crédito; \r\nOtro; \r\nNinguno; \r\nNo sabe; \r\nPrefiere no responder", 
                                                                                                                                                                                                                                                                                                                                                      "Opciones a determinar por cada uno de los paises en cuyos rangos se contemple la linea de corte del salario minimo", 
                                                                                                                                                                                                                                                                                                                                                      "No tiene ninguna fuente de ingresos; \r\nAhorros; \r\nTrabajo con empleador Autoempleo/Emprendimiento; \r\nCaridad; \r\nAsistencia humanitaria;         \r\nOtra fuente;                 \r\nNo sabe;  \r\nPrefiere no responder", 
                                                                                                                                                                                                                                                                                                                                                      "Si; \r\nNo; \r\nNo sabe; \r\nPrefiere no responder\r\n"), Umbrales = c("Todos los NNA que dicen que NO están inscritos en el sistema educativo formal", 
                                                                                                                                                                                                                                                                                                                                                                                                                              "Todos los NNA que dicen que NO están inscritos", "En el trabajo con su padre o madre o cuidador\r\nEn la vivienda, solo/a\r\nEn la vivienda donde vive el niño(a), al cuidado de una persona menor de 18 años", 
                                                                                                                                                                                                                                                                                                                                                                                                                              "Todos los NNA que hayan asistido menos de 5 días", "-", "-", 
                                                                                                                                                                                                                                                                                                                                                                                                                              "-", "-", "Todos los NNA que dicen que NO han tenido servicio educativo", 
                                                                                                                                                                                                                                                                                                                                                                                                                              "-", "-", "-", "-", "Personas que buscaron trabajo en edad laboral", 
                                                                                                                                                                                                                                                                                                                                                                                                                              "No", "No.", "No", "Si por nacionalidad", "En el trabajo\r\nBuscando trabajo\r\n", 
                                                                                                                                                                                                                                                                                                                                                                                                                              "Ninguno", "Ingresos por debajo del salario minimo", "No tiene ninguna fuente de ingresos\r\nCaridad\r\nAsistencia humanitaria", 
                                                                                                                                                                                                                                                                                                                                                                                                                              "-"), `Indicador Core PiN` = c("Si", "Si", "0", "Si", "No", "No", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                             "No", "No", "Si", "No", "No", "No", "No", "Sí", "Sí", "0", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                             "0", "Si", "0", "Si", "No", "Sí", "No"), `Formula de cálculo` = c("Número de NNA que no estan inscritos/Total de NNA en edad escolar \r\n\r\nNota: en la mayoria de paises es de 7 a 18 años, se puede adaptar de acuerdo al contexto. Incluir nota explicativa", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Número de NNA que no estan inscritos y que no cuentan con un cuidado adecuado/Total de NNA (de 0 a 3 años)", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "0", "Menos de 5 dias/ total de NNA", "-", "-", "-", "-", "Todos los NNA que dicen que NO han tenido servicio educativo / Todos los NNA en tránsito en edad escolar", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "-", "-", "-", "-", "Tasa de Desempleo (%) = (Número de Personas Desempleadas / Población Económicamente Activa) x 100", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Numero de personas en trabajos informales (sin contrato y/o sin seguridad social) / Total de miembros que mencionaron estar trabajando", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "0", "0", "Numero de hogares que se sienten discriminadas por nacionalidad en el ambito laboral/Total de personas encuestadas", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "0", "Personas que no tienen ningun producto financiero/Total de hogares", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Personas que ganan un ingreso por debajo del salario minimo/Total de personas que trabajan", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Número de personas encuestadas que no tienen ninguna fuente de ingresos o que viven de la caridad o la asistencia / Total de personas encuestadas", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Número de personas encuestadas que su ingreso no es suficiente para cubrir sus gastos durante el transito / Total de personas encuestadas"
                                                                                                                                                                                                                                                                                                                                                                                                                                                             ), `Unidad de medida` = c("Miembros de hogar", "Miembros de hogar", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "0", "Miembros de hogar", "Miembros de hogar", "Miembros de hogar", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "Miembros de hogar", "Miembros de hogar", "Miembros de grupo de viaje", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "Miembros de grupo de viaje", "Miembros de grupo de viaje", "Miembros de grupo de viaje", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "Miembros de grupo de viaje", "Miembros de hogar", "Miembros de hogar", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "0", "0", "Hogares", "Hogares", "Hogares", "Miembros de hogar", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "Grupo de viaje", "Grupo de viaje"), `Condición de relevancia` = c("NNA en edad escolar (de 0 a 18 años)", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "NNA  (de 0 a 3 años) \r\nNota: Si esta condicion cambia por pais se puede adaptar de acuerdo al contexto. Incluir nota explicativa", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "0", "NNA en edad escolar y que en la pregunta anterior hayan dicho si", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Depende del país, usualmente no aplica para niveles de atencion a la primera infancia, solo aplica a los niveles educativos de primaria, secundaria y bachillerato", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Si en la pregunta anterior contestó \"No\".\r\nDepende del país, usualmente mayores de 6 años que no hayan validado sus estudios", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Para los NNA que no están inscritos en edad escolar", "Para los NNA que están inscritos y asistieron menos de 5 días a la semana en promedio", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Grupos de viaje con NNA en edad escolar", "Grupos de viaje con NNA en edad escolar", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Para grupos de viaje con NNA que sí hayan recibido información", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Para grupos de viaje con NNA que sí hayan recibido información", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Para grupos de viaje con NNA que sí hayan recibido información", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Miembros de hogar que estan en edad de trabajar", "Miembros de hogar que estan trabajando", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Miembros de hogar que estan trabajando", "Miembros de hogar que estan trabajando", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "-", "Personas encuestadas que mencionaron que se sienten discriminadas por alguna razon", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "-", "Miembros de hogar que estan trabajando", "-", "-"), `Comentarios adicionales` = c("-", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "-", "-", "-", "-", "-", "-", "-", "-", "-")), row.names = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               -23L), class = c("tbl_df", "tbl", "data.frame"))


JNA2024Indicators <- SourceJNA2024Indicators

##-- Calling componets for shiny header  ----
tab_files <- list.files(path = "tabs", full.names = T, recursive = T)
tab_files <- tab_files[-grep(x = tab_files, pattern = "server")]

suppressMessages(lapply(tab_files, source))